# utils/cms_responses.py

CMS_RESPONSES = {
    "return policy": "🛍️ *Return Policy*\nYou may return unused items within 7 days of delivery. Please ensure the product is in original packaging.",
    "delivery": "🚚 *Delivery Info*\nWe deliver across India. Most orders are shipped within 24–48 hours and arrive in 2–5 working days.",
    "shipping": "📦 *Shipping Info*\nStandard and express shipping options available. You can choose at checkout.",
    "cash on delivery": "💵 *Cash on Delivery*\nYes, we support COD for orders under ₹5000. COD fee may apply.",
    "refund": "💰 *Refund Policy*\nRefunds are processed within 7 business days once the returned item is received and inspected.",
    "warranty": "🛡️ *Warranty Info*\nAll Aarogyaa Bharat products come with a 6-month warranty against manufacturing defects.",
    "payment": "💳 *Payment Options*\nWe accept UPI, Net Banking, Credit/Debit Cards, and Cash on Delivery.",
    "installation": "🛠️ *Installation Support*\nFor complex equipment like wheelchairs and hospital beds, we provide virtual or doorstep installation assistance in select cities.",
    "gst invoice": "🧾 *GST Invoice*\nYes, we provide GST-compliant invoices. Businesses can claim input tax credit by entering their GSTIN at checkout.",
    "bulk order": "📦 *Bulk Orders*\nWe offer bulk pricing for hospitals, clinics, NGOs, and resellers. Contact support for a custom quotation.",
    "contact": "📞 *Customer Support*\nYou can reach our support team at +91-XXXXXXXXXX or email support@aarogyaabharat.com.",
    "tracking": "📍 *Order Tracking*\nYou can track your order using the link sent to your email or SMS once it ships.",
    "cancellation": "❌ *Order Cancellation*\nYou can cancel an order before it is shipped. After dispatch, cancellation is not possible, but you can initiate a return.",
    "prescription": "📋 *Prescription Requirement*\nMost products don't require a prescription. For oxygen concentrators or similar, we may ask for one.",
    "availability": "🛒 *Product Availability*\nProducts marked 'In Stock' are available. Use 'Notify Me' on the product page for out-of-stock items.",
    "support": "🙋 *Medical Equipment Support*\nOur team includes certified technicians to assist with training and product guidance.",
    "maintenance": "🔧 *Maintenance Info*\nWe provide basic maintenance instructions with most products and support on call.",
    "guarantee": "✅ *Product Guarantee*\nWe guarantee authenticity and manufacturer-backed warranties.",
    "safety": "🔒 *Product Safety*\nAll medical equipment is CE/ISO certified and validated by professionals."
}

# Synonyms for intelligent matching
CMS_SYNONYMS = {
    "return": "return policy",
    "refund": "refund",
    "replace": "return policy",
    "delivery": "delivery",
    "ship": "shipping",
    "shipping": "shipping",
    "cod": "cash on delivery",
    "cash": "cash on delivery",
    "invoice": "gst invoice",
    "gst": "gst invoice",
    "bill": "gst invoice",
    "cancel": "cancellation",
    "cancellation": "cancellation",
    "track": "tracking",
    "order tracking": "tracking",
    "payment": "payment",
    "pay": "payment",
    "buy in bulk": "bulk order",
    "hospital order": "bulk order",
    "prescription": "prescription",
    "stock": "availability",
    "out of stock": "availability",
    "setup": "installation",
    "install": "installation",
    "support": "support",
    "repair": "maintenance",
    "warranty": "warranty",
    "guarantee": "guarantee",
    "safe": "safety",
    "safety": "safety",
    "helpline": "contact",
    "call": "contact",
    "phone": "contact"
}
